// Code generated by mockery v2.10.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ImageService is an autogenerated mock type for the ImageService type
type ImageService struct {
	mock.Mock
}

// CreateFile provides a mock function with given fields: w, r
func (_m *ImageService) CreateFile(w http.ResponseWriter, r *http.Request) error {
	ret := _m.Called(w, r)

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) error); ok {
		r0 = rf(w, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFile provides a mock function with given fields: w, r, filename
func (_m *ImageService) GetFile(w http.ResponseWriter, r *http.Request, filename string) error {
	ret := _m.Called(w, r, filename)

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, string) error); ok {
		r0 = rf(w, r, filename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
