version: '3.7'
services:
    file-service:
        image: file-services
        container_name: file-services
        ports:
          - 5000:5000
        environment:
          - API_PORT=5000
          - POSTGRES_DB=file_storage
          - POSTGRES_CONTAINER=postgres
          - POSTGRES_PORT=5432
          - POSTGRES_PWD=admin
          - REDIS_CONTAINER=redis
          - REDIS_PORT=6379
          - RABBIT_CONTAINER=guest:guest@rabbitmq
          - RABBIT_PORT=5672
        depends_on:
          - "redis"
          - "postgres"
          - "rabbitmq"
    postgres:
        image: postgres:latest
        restart: always
        container_name: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=admin
          - POSTGRES_DB=file_storage
        ports:
          - 5432:5432
        volumes:
            - ./db:/docker-entrypoint-initdb.d/
            - ./db/postgres-data:/var/lib/postgresql/data
    adminer:
      image: adminer:latest
      container_name: file_storage-adminer
      ports:
        - 8080:8080

    redis:
      image: redis:6.2-alpine
      restart: always
      container_name: redis
      ports:
        - 6379:6379
      command: redis-server --save 60 1 --loglevel warning 
      volumes:
        - ./db/redis-data:/data

    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - ./db/rabbitmq-data:/var/lib/rabbitmq/

volumes:
  postgres-data:
  redis-data:
