version: '3.7'
services:
    postgres:
        image: postgres:latest
        restart: always
        container_name: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=admin
          - POSTGRES_DB=file_storage
        ports:
          - 5432:5432
        volumes:
            - ./db:/docker-entrypoint-initdb.d/
            - ./db/postgres-data:/var/lib/postgresql/data
    adminer:
      image: adminer:latest
      ports:
        - 8080:8080
    redis:
      image: redis:6.2-alpine
      restart: always
      container_name: redis
      ports:
        - 6379:6379
      command: redis-server --save 60 1 --loglevel warning 
      volumes:
        - ./db/redis-data:/data

volumes:
  postgres-data:
  redis-data: